// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJO9tlMyZrD92aXnp1BLuib8tLvFervZQ',
    appId: '1:6746703710:web:ab6b61f56f3ccde65df1cf',
    messagingSenderId: '6746703710',
    projectId: 'chat-7d927',
    authDomain: 'chat-7d927.firebaseapp.com',
    databaseURL: 'https://chat-7d927-default-rtdb.firebaseio.com',
    storageBucket: 'chat-7d927.appspot.com',
    measurementId: 'G-9CEFVTC484',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs5WNlUvMw1wE9mAShg3Fu08nyQY0oY8E',
    appId: '1:6746703710:android:3462e9b76bf3d11e5df1cf',
    messagingSenderId: '6746703710',
    projectId: 'chat-7d927',
    databaseURL: 'https://chat-7d927-default-rtdb.firebaseio.com',
    storageBucket: 'chat-7d927.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJyi2GMyTC99VNEWA2ehrFcFwL7b8JzM0',
    appId: '1:6746703710:ios:95086d24ca1914945df1cf',
    messagingSenderId: '6746703710',
    projectId: 'chat-7d927',
    databaseURL: 'https://chat-7d927-default-rtdb.firebaseio.com',
    storageBucket: 'chat-7d927.appspot.com',
    androidClientId: '6746703710-8ffbmh27v9sfj49427mk439lqspm5btq.apps.googleusercontent.com',
    iosClientId: '6746703710-t60dpng5k48imdntdccnk9keo7l4epi1.apps.googleusercontent.com',
    iosBundleId: 'com.example.variable',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJyi2GMyTC99VNEWA2ehrFcFwL7b8JzM0',
    appId: '1:6746703710:ios:95086d24ca1914945df1cf',
    messagingSenderId: '6746703710',
    projectId: 'chat-7d927',
    databaseURL: 'https://chat-7d927-default-rtdb.firebaseio.com',
    storageBucket: 'chat-7d927.appspot.com',
    androidClientId: '6746703710-8ffbmh27v9sfj49427mk439lqspm5btq.apps.googleusercontent.com',
    iosClientId: '6746703710-t60dpng5k48imdntdccnk9keo7l4epi1.apps.googleusercontent.com',
    iosBundleId: 'com.example.variable',
  );
}
